elasticSearch:
  url: "http://192.168.222.240:9200"
host: "go-script-launch-video-conversion"
folders:
  - origin: "/Users/sleguin/Downloads/ZZ_test"
originExtensions:
  - ".ts"
destinationExtensions: ".mp4"
params:
  - "-e"
  - "x264"
  - "-R"
  - "44100"
  - "-B"
  - "128"
